version: "3.9"
name: portfolio
services:
  nextjs:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    container_name: next_portfolio
    restart: unless-stopped

    env_file:
      - ../../.env

    labels:
      - "traefik.enable=true"

      # Router domain Next.js
      - "traefik.http.routers.portfolio.rule=Host(`nafishandoko.my.id`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"

      # Port Next.js internal
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"

    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
